name: Run Tests
concurrency:
  group: run-tests-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - kotlin/**
jobs:
  run-kotlin-tests:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    uses: ./.github/workflows/run-kotlin-tests.yml
  run-swift-tests:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    uses: ./.github/workflows/run-swift-tests.yml
  run-integration-tests:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    needs:
      - run-kotlin-tests
      - run-swift-tests
    uses: ./.github/workflows/run-integration-tests.yml
  run-idea-tests:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    uses: ./.github/workflows/run-idea-tests.yml
